server:
  port: 8090

spring:
  main:
    allow-bean-definition-overriding: true
#   datasource:
#     driver-class-name: com.mysql.cj.jdbc.Driver
#     url: jdbc:mysql://mysql_microservice:3306/technical_support?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&&serverTimezone=UTC
#     username: ENC(s7HRRfxLOcFxweV3RG5r0Q==)
#     password: ENC(y0SDRnC6+wI+ddi/utiuSiwDmKB4o4w3)
#   liquibase:
#     change-log: /db/changelog/changelog-master.xml
#     enabled: true
#   jpa:
#     database-platform: org.hibernate.dialect.MySQL8Dialect
#     show-sql: true
#     hibernate:
#       ddl-auto: validate

jasypt:
  encryptor:
    bean: encryptorBean

services:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: admin
    password: admin
    exchange: support
    routingKey: support
    queue: support
    
external:
  mail:
    key: ENC(K7d4bRWHYCdbITscwoIqPIi9SZx6rbteqan1VTjzniHFyBzcsTb5rogbtnljp3hh)
    secret: ENC(GXKUX11aEp43FY4B8CpX79OmUI9ryLyY6yHSLBz33RSWAFf47jYk+c1SlLYUuKdG)
    from: ENC(H4dZAhFspV/470tWbOY7Jk6mllp/EYJYns4oVTKaDqHkMqYtrtBK8Q==)
    theme: "Вам письмо от технической поддержки ZeroneNetwork!!!"

