server:
  port: 8086
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/network_db?allowPublicKeyRetrieval=true&useSSL=false&&serverTimezone=UTC&autoReconnect=true&maxReconnects=10
    username: ENC(PWu0QZMimWB0juSsNBfwTQ==)
    password: ENC(iQN1pkOYWMp0W+FUF3h3XeKSG3ljVSrp)
  liquibase:
    change-log: /db/changelog/changelog.yml
  jpa:
    show-sql: false
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      ddl-auto: validate
  servlet:
    multipart:
      max-file-size: -1
  redis:
    host: localhost
    port: 6379
    password: ENC(X2BUlR94IUPOPa1D7mGtbSnP6cbaWPMT)
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

registration:
  confirm:
    need: false
    url: "http://147.78.64.57:8086/api/v1/account/registration_complete"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  security:
    enabled: false

cloud:
  aws:
    credentials:
      access-key: bjwgIspnfqIQsSEvsivr
      secret-key: ct15ZUAOTO0ARY-_bCB4QmlR2IREqDpbGgMN7Z1b
    sns:
      enabled: false #Amazon SNS disabling
    s3:
      region: ${cloud.yandex.region} #This need for run application
    sqs:
      endpoint: https://message-queue.api.cloud.yandex.net/ #endpoint from yandex cloud documentation
  yandex:
    region: ru-central1 #region from yandex.cloud documentation
message:
  queue:
    outgoing: support_message_queue

external:
  vk:
    id: ENC(m7rHhgvZf1a3XykimmtX9A==)
    token: ENC(0FWZ/Ebbh5M0GV/ZD8TcXU1ISRbcusF9MrjiZsUnR4Vf4Hv8l7sp32S4w/KWqNsnLI7ppZCPy3ZztKJxXLGkhpBEkJXeEZpE6NFIDCts6BY=)
  cloudinary:
    cloud: ENC(Vfhff27NWtbJpMagmXDrAPdoUn5Wl0BP)
    key: ENC(Dw9PMgrkxd0Q7YTIBowaLFI/ixt2nvHf)
    secret: ENC(hQVnqsRAm3jW1tjWc3zDAOu19ppToSJ7czBD5CHa0E6coGq36y7wVA==)
  mail:
    key: ENC(K7d4bRWHYCdbITscwoIqPIi9SZx6rbteqan1VTjzniHFyBzcsTb5rogbtnljp3hh)
    secret: ENC(GXKUX11aEp43FY4B8CpX79OmUI9ryLyY6yHSLBz33RSWAFf47jYk+c1SlLYUuKdG)
    from: ENC(H4dZAhFspV/470tWbOY7Jk6mllp/EYJYns4oVTKaDqHkMqYtrtBK8Q==)
    theme: "Письмо от Zeronetwork"

jasypt:
  encryptor:
    bean: encryptorBean

ws: 
  server: 
    host: "0.0.0.0"
    port: 1111
    
cors:
  urls:
    - http://localhost:8086/
    - http://localhost:8080/
    - http://127.0.0.1:8086/
    - http://127.0.0.1:8080/
    - http://localhost/
    - http://localhost
    - http://127.0.0.1/
    - http://195.234.208.58/
    - http://localhost:80/
    - http://127.0.0.1:80/
    - http://195.234.208.58:80/
    - http://www.zeronenetwork.design/
    - http://10.186.0.2:8086/
    - http://10.186.0.2/%22

soft:
  person:
    month: 3
  post: 
    day: 7
  comment:
    day: 1
